// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/event.proto

package lvi;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BatchEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lvi.BatchEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
     * @return Whether the actor field is set.
     */
    boolean hasActor();
    /**
     * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
     * @return The actor.
     */
    lvi.ActorOuterClass.Actor getActor();
    /**
     * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
     */
    lvi.ActorOuterClass.ActorOrBuilder getActorOrBuilder();
  }
  /**
   * Protobuf type {@code lvi.BatchEvent}
   */
  public  static final class BatchEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lvi.BatchEvent)
      BatchEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BatchEvent.newBuilder() to construct.
    private BatchEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BatchEvent() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BatchEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BatchEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              lvi.ActorOuterClass.Actor.Builder subBuilder = null;
              if (actor_ != null) {
                subBuilder = actor_.toBuilder();
              }
              actor_ = input.readMessage(lvi.ActorOuterClass.Actor.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(actor_);
                actor_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lvi.Event.internal_static_lvi_BatchEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lvi.Event.internal_static_lvi_BatchEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lvi.Event.BatchEvent.class, lvi.Event.BatchEvent.Builder.class);
    }

    public static final int ACTOR_FIELD_NUMBER = 2;
    private lvi.ActorOuterClass.Actor actor_;
    /**
     * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
     * @return Whether the actor field is set.
     */
    public boolean hasActor() {
      return actor_ != null;
    }
    /**
     * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
     * @return The actor.
     */
    public lvi.ActorOuterClass.Actor getActor() {
      return actor_ == null ? lvi.ActorOuterClass.Actor.getDefaultInstance() : actor_;
    }
    /**
     * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
     */
    public lvi.ActorOuterClass.ActorOrBuilder getActorOrBuilder() {
      return getActor();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (actor_ != null) {
        output.writeMessage(2, getActor());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (actor_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getActor());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lvi.Event.BatchEvent)) {
        return super.equals(obj);
      }
      lvi.Event.BatchEvent other = (lvi.Event.BatchEvent) obj;

      if (hasActor() != other.hasActor()) return false;
      if (hasActor()) {
        if (!getActor()
            .equals(other.getActor())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasActor()) {
        hash = (37 * hash) + ACTOR_FIELD_NUMBER;
        hash = (53 * hash) + getActor().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lvi.Event.BatchEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lvi.Event.BatchEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lvi.Event.BatchEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lvi.Event.BatchEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lvi.Event.BatchEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lvi.Event.BatchEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lvi.Event.BatchEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lvi.Event.BatchEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static lvi.Event.BatchEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static lvi.Event.BatchEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lvi.Event.BatchEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lvi.Event.BatchEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lvi.Event.BatchEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lvi.BatchEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lvi.BatchEvent)
        lvi.Event.BatchEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lvi.Event.internal_static_lvi_BatchEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lvi.Event.internal_static_lvi_BatchEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lvi.Event.BatchEvent.class, lvi.Event.BatchEvent.Builder.class);
      }

      // Construct using lvi.Event.BatchEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (actorBuilder_ == null) {
          actor_ = null;
        } else {
          actor_ = null;
          actorBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lvi.Event.internal_static_lvi_BatchEvent_descriptor;
      }

      @java.lang.Override
      public lvi.Event.BatchEvent getDefaultInstanceForType() {
        return lvi.Event.BatchEvent.getDefaultInstance();
      }

      @java.lang.Override
      public lvi.Event.BatchEvent build() {
        lvi.Event.BatchEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lvi.Event.BatchEvent buildPartial() {
        lvi.Event.BatchEvent result = new lvi.Event.BatchEvent(this);
        if (actorBuilder_ == null) {
          result.actor_ = actor_;
        } else {
          result.actor_ = actorBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lvi.Event.BatchEvent) {
          return mergeFrom((lvi.Event.BatchEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lvi.Event.BatchEvent other) {
        if (other == lvi.Event.BatchEvent.getDefaultInstance()) return this;
        if (other.hasActor()) {
          mergeActor(other.getActor());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        lvi.Event.BatchEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (lvi.Event.BatchEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private lvi.ActorOuterClass.Actor actor_;
      private com.google.protobuf.SingleFieldBuilderV3<
          lvi.ActorOuterClass.Actor, lvi.ActorOuterClass.Actor.Builder, lvi.ActorOuterClass.ActorOrBuilder> actorBuilder_;
      /**
       * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
       * @return Whether the actor field is set.
       */
      public boolean hasActor() {
        return actorBuilder_ != null || actor_ != null;
      }
      /**
       * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
       * @return The actor.
       */
      public lvi.ActorOuterClass.Actor getActor() {
        if (actorBuilder_ == null) {
          return actor_ == null ? lvi.ActorOuterClass.Actor.getDefaultInstance() : actor_;
        } else {
          return actorBuilder_.getMessage();
        }
      }
      /**
       * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public Builder setActor(lvi.ActorOuterClass.Actor value) {
        if (actorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          actor_ = value;
          onChanged();
        } else {
          actorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public Builder setActor(
          lvi.ActorOuterClass.Actor.Builder builderForValue) {
        if (actorBuilder_ == null) {
          actor_ = builderForValue.build();
          onChanged();
        } else {
          actorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public Builder mergeActor(lvi.ActorOuterClass.Actor value) {
        if (actorBuilder_ == null) {
          if (actor_ != null) {
            actor_ =
              lvi.ActorOuterClass.Actor.newBuilder(actor_).mergeFrom(value).buildPartial();
          } else {
            actor_ = value;
          }
          onChanged();
        } else {
          actorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public Builder clearActor() {
        if (actorBuilder_ == null) {
          actor_ = null;
          onChanged();
        } else {
          actor_ = null;
          actorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public lvi.ActorOuterClass.Actor.Builder getActorBuilder() {
        
        onChanged();
        return getActorFieldBuilder().getBuilder();
      }
      /**
       * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public lvi.ActorOuterClass.ActorOrBuilder getActorOrBuilder() {
        if (actorBuilder_ != null) {
          return actorBuilder_.getMessageOrBuilder();
        } else {
          return actor_ == null ?
              lvi.ActorOuterClass.Actor.getDefaultInstance() : actor_;
        }
      }
      /**
       * <code>.lvi.Actor actor = 2 [(.lvi.required) = true, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          lvi.ActorOuterClass.Actor, lvi.ActorOuterClass.Actor.Builder, lvi.ActorOuterClass.ActorOrBuilder> 
          getActorFieldBuilder() {
        if (actorBuilder_ == null) {
          actorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              lvi.ActorOuterClass.Actor, lvi.ActorOuterClass.Actor.Builder, lvi.ActorOuterClass.ActorOrBuilder>(
                  getActor(),
                  getParentForChildren(),
                  isClean());
          actor_ = null;
        }
        return actorBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lvi.BatchEvent)
    }

    // @@protoc_insertion_point(class_scope:lvi.BatchEvent)
    private static final lvi.Event.BatchEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lvi.Event.BatchEvent();
    }

    public static lvi.Event.BatchEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BatchEvent>
        PARSER = new com.google.protobuf.AbstractParser<BatchEvent>() {
      @java.lang.Override
      public BatchEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BatchEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BatchEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BatchEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lvi.Event.BatchEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EventBatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lvi.EventBatch)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
     * @return Whether the client field is set.
     */
    boolean hasClient();
    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
     * @return The client.
     */
    lvi.ClientOuterClass.Client getClient();
    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
     */
    lvi.ClientOuterClass.ClientOrBuilder getClientOrBuilder();

    /**
     * <code>repeated .lvi.BatchEvent events = 2;</code>
     */
    java.util.List<lvi.Event.BatchEvent> 
        getEventsList();
    /**
     * <code>repeated .lvi.BatchEvent events = 2;</code>
     */
    lvi.Event.BatchEvent getEvents(int index);
    /**
     * <code>repeated .lvi.BatchEvent events = 2;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated .lvi.BatchEvent events = 2;</code>
     */
    java.util.List<? extends lvi.Event.BatchEventOrBuilder> 
        getEventsOrBuilderList();
    /**
     * <code>repeated .lvi.BatchEvent events = 2;</code>
     */
    lvi.Event.BatchEventOrBuilder getEventsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code lvi.EventBatch}
   */
  public  static final class EventBatch extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lvi.EventBatch)
      EventBatchOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventBatch.newBuilder() to construct.
    private EventBatch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventBatch() {
      events_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventBatch();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EventBatch(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              lvi.ClientOuterClass.Client.Builder subBuilder = null;
              if (client_ != null) {
                subBuilder = client_.toBuilder();
              }
              client_ = input.readMessage(lvi.ClientOuterClass.Client.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(client_);
                client_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                events_ = new java.util.ArrayList<lvi.Event.BatchEvent>();
                mutable_bitField0_ |= 0x00000001;
              }
              events_.add(
                  input.readMessage(lvi.Event.BatchEvent.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lvi.Event.internal_static_lvi_EventBatch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lvi.Event.internal_static_lvi_EventBatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lvi.Event.EventBatch.class, lvi.Event.EventBatch.Builder.class);
    }

    public static final int CLIENT_FIELD_NUMBER = 1;
    private lvi.ClientOuterClass.Client client_;
    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
     * @return Whether the client field is set.
     */
    public boolean hasClient() {
      return client_ != null;
    }
    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
     * @return The client.
     */
    public lvi.ClientOuterClass.Client getClient() {
      return client_ == null ? lvi.ClientOuterClass.Client.getDefaultInstance() : client_;
    }
    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
     */
    public lvi.ClientOuterClass.ClientOrBuilder getClientOrBuilder() {
      return getClient();
    }

    public static final int EVENTS_FIELD_NUMBER = 2;
    private java.util.List<lvi.Event.BatchEvent> events_;
    /**
     * <code>repeated .lvi.BatchEvent events = 2;</code>
     */
    public java.util.List<lvi.Event.BatchEvent> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .lvi.BatchEvent events = 2;</code>
     */
    public java.util.List<? extends lvi.Event.BatchEventOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .lvi.BatchEvent events = 2;</code>
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .lvi.BatchEvent events = 2;</code>
     */
    public lvi.Event.BatchEvent getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .lvi.BatchEvent events = 2;</code>
     */
    public lvi.Event.BatchEventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (client_ != null) {
        output.writeMessage(1, getClient());
      }
      for (int i = 0; i < events_.size(); i++) {
        output.writeMessage(2, events_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (client_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getClient());
      }
      for (int i = 0; i < events_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, events_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lvi.Event.EventBatch)) {
        return super.equals(obj);
      }
      lvi.Event.EventBatch other = (lvi.Event.EventBatch) obj;

      if (hasClient() != other.hasClient()) return false;
      if (hasClient()) {
        if (!getClient()
            .equals(other.getClient())) return false;
      }
      if (!getEventsList()
          .equals(other.getEventsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasClient()) {
        hash = (37 * hash) + CLIENT_FIELD_NUMBER;
        hash = (53 * hash) + getClient().hashCode();
      }
      if (getEventsCount() > 0) {
        hash = (37 * hash) + EVENTS_FIELD_NUMBER;
        hash = (53 * hash) + getEventsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lvi.Event.EventBatch parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lvi.Event.EventBatch parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lvi.Event.EventBatch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lvi.Event.EventBatch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lvi.Event.EventBatch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lvi.Event.EventBatch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lvi.Event.EventBatch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lvi.Event.EventBatch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static lvi.Event.EventBatch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static lvi.Event.EventBatch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lvi.Event.EventBatch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static lvi.Event.EventBatch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lvi.Event.EventBatch prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lvi.EventBatch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lvi.EventBatch)
        lvi.Event.EventBatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lvi.Event.internal_static_lvi_EventBatch_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lvi.Event.internal_static_lvi_EventBatch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lvi.Event.EventBatch.class, lvi.Event.EventBatch.Builder.class);
      }

      // Construct using lvi.Event.EventBatch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEventsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (clientBuilder_ == null) {
          client_ = null;
        } else {
          client_ = null;
          clientBuilder_ = null;
        }
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lvi.Event.internal_static_lvi_EventBatch_descriptor;
      }

      @java.lang.Override
      public lvi.Event.EventBatch getDefaultInstanceForType() {
        return lvi.Event.EventBatch.getDefaultInstance();
      }

      @java.lang.Override
      public lvi.Event.EventBatch build() {
        lvi.Event.EventBatch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lvi.Event.EventBatch buildPartial() {
        lvi.Event.EventBatch result = new lvi.Event.EventBatch(this);
        int from_bitField0_ = bitField0_;
        if (clientBuilder_ == null) {
          result.client_ = client_;
        } else {
          result.client_ = clientBuilder_.build();
        }
        if (eventsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            events_ = java.util.Collections.unmodifiableList(events_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.events_ = events_;
        } else {
          result.events_ = eventsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lvi.Event.EventBatch) {
          return mergeFrom((lvi.Event.EventBatch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lvi.Event.EventBatch other) {
        if (other == lvi.Event.EventBatch.getDefaultInstance()) return this;
        if (other.hasClient()) {
          mergeClient(other.getClient());
        }
        if (eventsBuilder_ == null) {
          if (!other.events_.isEmpty()) {
            if (events_.isEmpty()) {
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEventsIsMutable();
              events_.addAll(other.events_);
            }
            onChanged();
          }
        } else {
          if (!other.events_.isEmpty()) {
            if (eventsBuilder_.isEmpty()) {
              eventsBuilder_.dispose();
              eventsBuilder_ = null;
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000001);
              eventsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEventsFieldBuilder() : null;
            } else {
              eventsBuilder_.addAllMessages(other.events_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        lvi.Event.EventBatch parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (lvi.Event.EventBatch) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private lvi.ClientOuterClass.Client client_;
      private com.google.protobuf.SingleFieldBuilderV3<
          lvi.ClientOuterClass.Client, lvi.ClientOuterClass.Client.Builder, lvi.ClientOuterClass.ClientOrBuilder> clientBuilder_;
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
       * @return Whether the client field is set.
       */
      public boolean hasClient() {
        return clientBuilder_ != null || client_ != null;
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
       * @return The client.
       */
      public lvi.ClientOuterClass.Client getClient() {
        if (clientBuilder_ == null) {
          return client_ == null ? lvi.ClientOuterClass.Client.getDefaultInstance() : client_;
        } else {
          return clientBuilder_.getMessage();
        }
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
       */
      public Builder setClient(lvi.ClientOuterClass.Client value) {
        if (clientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          client_ = value;
          onChanged();
        } else {
          clientBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
       */
      public Builder setClient(
          lvi.ClientOuterClass.Client.Builder builderForValue) {
        if (clientBuilder_ == null) {
          client_ = builderForValue.build();
          onChanged();
        } else {
          clientBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
       */
      public Builder mergeClient(lvi.ClientOuterClass.Client value) {
        if (clientBuilder_ == null) {
          if (client_ != null) {
            client_ =
              lvi.ClientOuterClass.Client.newBuilder(client_).mergeFrom(value).buildPartial();
          } else {
            client_ = value;
          }
          onChanged();
        } else {
          clientBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
       */
      public Builder clearClient() {
        if (clientBuilder_ == null) {
          client_ = null;
          onChanged();
        } else {
          client_ = null;
          clientBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
       */
      public lvi.ClientOuterClass.Client.Builder getClientBuilder() {
        
        onChanged();
        return getClientFieldBuilder().getBuilder();
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
       */
      public lvi.ClientOuterClass.ClientOrBuilder getClientOrBuilder() {
        if (clientBuilder_ != null) {
          return clientBuilder_.getMessageOrBuilder();
        } else {
          return client_ == null ?
              lvi.ClientOuterClass.Client.getDefaultInstance() : client_;
        }
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = true, (.lvi.description) = "Owner of the event"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          lvi.ClientOuterClass.Client, lvi.ClientOuterClass.Client.Builder, lvi.ClientOuterClass.ClientOrBuilder> 
          getClientFieldBuilder() {
        if (clientBuilder_ == null) {
          clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              lvi.ClientOuterClass.Client, lvi.ClientOuterClass.Client.Builder, lvi.ClientOuterClass.ClientOrBuilder>(
                  getClient(),
                  getParentForChildren(),
                  isClean());
          client_ = null;
        }
        return clientBuilder_;
      }

      private java.util.List<lvi.Event.BatchEvent> events_ =
        java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          events_ = new java.util.ArrayList<lvi.Event.BatchEvent>(events_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          lvi.Event.BatchEvent, lvi.Event.BatchEvent.Builder, lvi.Event.BatchEventOrBuilder> eventsBuilder_;

      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public java.util.List<lvi.Event.BatchEvent> getEventsList() {
        if (eventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(events_);
        } else {
          return eventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public int getEventsCount() {
        if (eventsBuilder_ == null) {
          return events_.size();
        } else {
          return eventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public lvi.Event.BatchEvent getEvents(int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);
        } else {
          return eventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public Builder setEvents(
          int index, lvi.Event.BatchEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.set(index, value);
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public Builder setEvents(
          int index, lvi.Event.BatchEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public Builder addEvents(lvi.Event.BatchEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public Builder addEvents(
          int index, lvi.Event.BatchEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(index, value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public Builder addEvents(
          lvi.Event.BatchEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public Builder addEvents(
          int index, lvi.Event.BatchEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends lvi.Event.BatchEvent> values) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, events_);
          onChanged();
        } else {
          eventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public Builder clearEvents() {
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public Builder removeEvents(int index) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.remove(index);
          onChanged();
        } else {
          eventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public lvi.Event.BatchEvent.Builder getEventsBuilder(
          int index) {
        return getEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public lvi.Event.BatchEventOrBuilder getEventsOrBuilder(
          int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);  } else {
          return eventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public java.util.List<? extends lvi.Event.BatchEventOrBuilder> 
           getEventsOrBuilderList() {
        if (eventsBuilder_ != null) {
          return eventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(events_);
        }
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public lvi.Event.BatchEvent.Builder addEventsBuilder() {
        return getEventsFieldBuilder().addBuilder(
            lvi.Event.BatchEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public lvi.Event.BatchEvent.Builder addEventsBuilder(
          int index) {
        return getEventsFieldBuilder().addBuilder(
            index, lvi.Event.BatchEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2;</code>
       */
      public java.util.List<lvi.Event.BatchEvent.Builder> 
           getEventsBuilderList() {
        return getEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          lvi.Event.BatchEvent, lvi.Event.BatchEvent.Builder, lvi.Event.BatchEventOrBuilder> 
          getEventsFieldBuilder() {
        if (eventsBuilder_ == null) {
          eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              lvi.Event.BatchEvent, lvi.Event.BatchEvent.Builder, lvi.Event.BatchEventOrBuilder>(
                  events_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        return eventsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lvi.EventBatch)
    }

    // @@protoc_insertion_point(class_scope:lvi.EventBatch)
    private static final lvi.Event.EventBatch DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lvi.Event.EventBatch();
    }

    public static lvi.Event.EventBatch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventBatch>
        PARSER = new com.google.protobuf.AbstractParser<EventBatch>() {
      @java.lang.Override
      public EventBatch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventBatch(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventBatch> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventBatch> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lvi.Event.EventBatch getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lvi_BatchEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lvi_BatchEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lvi_EventBatch_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lvi_EventBatch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022protos/event.proto\022\003lvi\032\035protos/bigque" +
      "ry_options.proto\032\023protos/client.proto\032\022p" +
      "rotos/actor.proto\"M\n\nBatchEvent\022?\n\005actor" +
      "\030\002 \001(\0132\n.lvi.ActorB$\220?\001\242?\036Actor concerne" +
      "d with the event\"t\n\nEventBatch\0225\n\006client" +
      "\030\001 \001(\0132\013.lvi.ClientB\030\220?\001\242?\022Owner of the " +
      "event\022\037\n\006events\030\002 \003(\0132\017.lvi.BatchEvent:\016" +
      "\220\202\031\001\232\202\031\006eventsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          lvi.BigqueryOptions.getDescriptor(),
          lvi.ClientOuterClass.getDescriptor(),
          lvi.ActorOuterClass.getDescriptor(),
        });
    internal_static_lvi_BatchEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lvi_BatchEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lvi_BatchEvent_descriptor,
        new java.lang.String[] { "Actor", });
    internal_static_lvi_EventBatch_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lvi_EventBatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lvi_EventBatch_descriptor,
        new java.lang.String[] { "Client", "Events", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(lvi.BigqueryOptions.batchField);
    registry.add(lvi.BigqueryOptions.description);
    registry.add(lvi.BigqueryOptions.required);
    registry.add(lvi.BigqueryOptions.tableRoot);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    lvi.BigqueryOptions.getDescriptor();
    lvi.ClientOuterClass.getDescriptor();
    lvi.ActorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
