# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/actor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import bigquery_options_pb2 as protos_dot_bigquery__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/actor.proto',
  package='lvi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12protos/actor.proto\x12\x03lvi\x1a\x1dprotos/bigquery_options.proto\")\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\t\"k\n\x05\x41\x63tor\x12\x34\n\x06userId\x18\x01 \x01(\x03\x42$\x90?\x01\xa2?\x1eIdentifier in the master table\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x1d\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x0c.lvi.Addressb\x06proto3'
  ,
  dependencies=[protos_dot_bigquery__options__pb2.DESCRIPTOR,])




_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='lvi.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='street', full_name='lvi.Address.street', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='lvi.Address.number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=99,
)


_ACTOR = _descriptor.Descriptor(
  name='Actor',
  full_name='lvi.Actor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='lvi.Actor.userId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\220?\001\242?\036Identifier in the master table', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='lvi.Actor.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='lvi.Actor.address', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=208,
)

_ACTOR.fields_by_name['address'].message_type = _ADDRESS
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['Actor'] = _ACTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'protos.actor_pb2'
  # @@protoc_insertion_point(class_scope:lvi.Address)
  })
_sym_db.RegisterMessage(Address)

Actor = _reflection.GeneratedProtocolMessageType('Actor', (_message.Message,), {
  'DESCRIPTOR' : _ACTOR,
  '__module__' : 'protos.actor_pb2'
  # @@protoc_insertion_point(class_scope:lvi.Actor)
  })
_sym_db.RegisterMessage(Actor)


_ACTOR.fields_by_name['userId']._options = None
# @@protoc_insertion_point(module_scope)
