# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/bigquery_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/bigquery_options.proto',
  package='lvi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1dprotos/bigquery_options.proto\x12\x03lvi\x1a google/protobuf/descriptor.proto:5\n\ntable_root\x12\x1f.google.protobuf.MessageOptions\x18\xa2\x90\x03 \x01(\x08:6\n\x0b\x62\x61tch_field\x12\x1f.google.protobuf.MessageOptions\x18\xa3\x90\x03 \x01(\t:0\n\x08required\x12\x1d.google.protobuf.FieldOptions\x18\xf2\x07 \x01(\x08:3\n\x0b\x64\x65scription\x12\x1d.google.protobuf.FieldOptions\x18\xf4\x07 \x01(\tb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


TABLE_ROOT_FIELD_NUMBER = 51234
table_root = _descriptor.FieldDescriptor(
  name='table_root', full_name='lvi.table_root', index=0,
  number=51234, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
BATCH_FIELD_FIELD_NUMBER = 51235
batch_field = _descriptor.FieldDescriptor(
  name='batch_field', full_name='lvi.batch_field', index=1,
  number=51235, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
REQUIRED_FIELD_NUMBER = 1010
required = _descriptor.FieldDescriptor(
  name='required', full_name='lvi.required', index=2,
  number=1010, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
DESCRIPTION_FIELD_NUMBER = 1012
description = _descriptor.FieldDescriptor(
  name='description', full_name='lvi.description', index=3,
  number=1012, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

DESCRIPTOR.extensions_by_name['table_root'] = table_root
DESCRIPTOR.extensions_by_name['batch_field'] = batch_field
DESCRIPTOR.extensions_by_name['required'] = required
DESCRIPTOR.extensions_by_name['description'] = description
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(table_root)
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(batch_field)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(required)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(description)

# @@protoc_insertion_point(module_scope)
