# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/client.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import bigquery_options_pb2 as protos_dot_bigquery__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/client.proto',
  package='lvi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13protos/client.proto\x12\x03lvi\x1a\x1dprotos/bigquery_options.proto\"P\n\x06\x43lient\x12\x38\n\x08tenantId\x18\x01 \x01(\x03\x42&\x90?\x01\xa2? Identifier in the client catalog\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3'
  ,
  dependencies=[protos_dot_bigquery__options__pb2.DESCRIPTOR,])




_CLIENT = _descriptor.Descriptor(
  name='Client',
  full_name='lvi.Client',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tenantId', full_name='lvi.Client.tenantId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\220?\001\242? Identifier in the client catalog', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='lvi.Client.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['Client'] = _CLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Client = _reflection.GeneratedProtocolMessageType('Client', (_message.Message,), {
  'DESCRIPTOR' : _CLIENT,
  '__module__' : 'protos.client_pb2'
  # @@protoc_insertion_point(class_scope:lvi.Client)
  })
_sym_db.RegisterMessage(Client)


_CLIENT.fields_by_name['tenantId']._options = None
# @@protoc_insertion_point(module_scope)
