# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/event.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import bigquery_options_pb2 as protos_dot_bigquery__options__pb2
from protos import client_pb2 as protos_dot_client__pb2
from protos import actor_pb2 as protos_dot_actor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/event.proto',
  package='lvi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12protos/event.proto\x12\x03lvi\x1a\x1dprotos/bigquery_options.proto\x1a\x13protos/client.proto\x1a\x12protos/actor.proto\"M\n\nBatchEvent\x12?\n\x05\x61\x63tor\x18\x02 \x01(\x0b\x32\n.lvi.ActorB$\x90?\x01\xa2?\x1e\x41\x63tor concerned with the event\"o\n\nEventBatch\x12\x35\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x0b.lvi.ClientB\x18\x90?\x01\xa2?\x12Owner of the event\x12$\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x0f.lvi.BatchEventB\x03\x98?\x01:\x04\x90\x82\x19\x01\x62\x06proto3'
  ,
  dependencies=[protos_dot_bigquery__options__pb2.DESCRIPTOR,protos_dot_client__pb2.DESCRIPTOR,protos_dot_actor__pb2.DESCRIPTOR,])




_BATCHEVENT = _descriptor.Descriptor(
  name='BatchEvent',
  full_name='lvi.BatchEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actor', full_name='lvi.BatchEvent.actor', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\220?\001\242?\036Actor concerned with the event', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=176,
)


_EVENTBATCH = _descriptor.Descriptor(
  name='EventBatch',
  full_name='lvi.EventBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='lvi.EventBatch.client', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\220?\001\242?\022Owner of the event', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='lvi.EventBatch.events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\230?\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\220\202\031\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=289,
)

_BATCHEVENT.fields_by_name['actor'].message_type = protos_dot_actor__pb2._ACTOR
_EVENTBATCH.fields_by_name['client'].message_type = protos_dot_client__pb2._CLIENT
_EVENTBATCH.fields_by_name['events'].message_type = _BATCHEVENT
DESCRIPTOR.message_types_by_name['BatchEvent'] = _BATCHEVENT
DESCRIPTOR.message_types_by_name['EventBatch'] = _EVENTBATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BatchEvent = _reflection.GeneratedProtocolMessageType('BatchEvent', (_message.Message,), {
  'DESCRIPTOR' : _BATCHEVENT,
  '__module__' : 'protos.event_pb2'
  # @@protoc_insertion_point(class_scope:lvi.BatchEvent)
  })
_sym_db.RegisterMessage(BatchEvent)

EventBatch = _reflection.GeneratedProtocolMessageType('EventBatch', (_message.Message,), {
  'DESCRIPTOR' : _EVENTBATCH,
  '__module__' : 'protos.event_pb2'
  # @@protoc_insertion_point(class_scope:lvi.EventBatch)
  })
_sym_db.RegisterMessage(EventBatch)


_BATCHEVENT.fields_by_name['actor']._options = None
_EVENTBATCH.fields_by_name['client']._options = None
_EVENTBATCH.fields_by_name['events']._options = None
_EVENTBATCH._options = None
# @@protoc_insertion_point(module_scope)
