// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/event.proto

package lvi;

public final class EventOuterClass {
  private EventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lvi.Tag)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tag_name = 1;</code>
     * @return The tagName.
     */
    String getTagName();
    /**
     * <code>string tag_name = 1;</code>
     * @return The bytes for tagName.
     */
    com.google.protobuf.ByteString
        getTagNameBytes();

    /**
     * <code>string tag_code = 2;</code>
     * @return The tagCode.
     */
    String getTagCode();
    /**
     * <code>string tag_code = 2;</code>
     * @return The bytes for tagCode.
     */
    com.google.protobuf.ByteString
        getTagCodeBytes();

    /**
     * <code>string tag_namespace = 3;</code>
     * @return The tagNamespace.
     */
    String getTagNamespace();
    /**
     * <code>string tag_namespace = 3;</code>
     * @return The bytes for tagNamespace.
     */
    com.google.protobuf.ByteString
        getTagNamespaceBytes();
  }
  /**
   * Protobuf type {@code lvi.Tag}
   */
  public static final class Tag extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lvi.Tag)
      TagOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tag.newBuilder() to construct.
    private Tag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tag() {
      tagName_ = "";
      tagCode_ = "";
      tagNamespace_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Tag();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tag(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              tagName_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              tagCode_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              tagNamespace_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventOuterClass.internal_static_lvi_Tag_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventOuterClass.internal_static_lvi_Tag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Tag.class, Builder.class);
    }

    public static final int TAG_NAME_FIELD_NUMBER = 1;
    private volatile Object tagName_;
    /**
     * <code>string tag_name = 1;</code>
     * @return The tagName.
     */
    @Override
    public String getTagName() {
      Object ref = tagName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tagName_ = s;
        return s;
      }
    }
    /**
     * <code>string tag_name = 1;</code>
     * @return The bytes for tagName.
     */
    @Override
    public com.google.protobuf.ByteString
        getTagNameBytes() {
      Object ref = tagName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tagName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAG_CODE_FIELD_NUMBER = 2;
    private volatile Object tagCode_;
    /**
     * <code>string tag_code = 2;</code>
     * @return The tagCode.
     */
    @Override
    public String getTagCode() {
      Object ref = tagCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tagCode_ = s;
        return s;
      }
    }
    /**
     * <code>string tag_code = 2;</code>
     * @return The bytes for tagCode.
     */
    @Override
    public com.google.protobuf.ByteString
        getTagCodeBytes() {
      Object ref = tagCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tagCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAG_NAMESPACE_FIELD_NUMBER = 3;
    private volatile Object tagNamespace_;
    /**
     * <code>string tag_namespace = 3;</code>
     * @return The tagNamespace.
     */
    @Override
    public String getTagNamespace() {
      Object ref = tagNamespace_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tagNamespace_ = s;
        return s;
      }
    }
    /**
     * <code>string tag_namespace = 3;</code>
     * @return The bytes for tagNamespace.
     */
    @Override
    public com.google.protobuf.ByteString
        getTagNamespaceBytes() {
      Object ref = tagNamespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tagNamespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTagNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tagName_);
      }
      if (!getTagCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tagCode_);
      }
      if (!getTagNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tagNamespace_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTagNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tagName_);
      }
      if (!getTagCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tagCode_);
      }
      if (!getTagNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tagNamespace_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Tag)) {
        return super.equals(obj);
      }
      Tag other = (Tag) obj;

      if (!getTagName()
          .equals(other.getTagName())) return false;
      if (!getTagCode()
          .equals(other.getTagCode())) return false;
      if (!getTagNamespace()
          .equals(other.getTagNamespace())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TAG_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTagName().hashCode();
      hash = (37 * hash) + TAG_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getTagCode().hashCode();
      hash = (37 * hash) + TAG_NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getTagNamespace().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Tag parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tag parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Tag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Tag prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lvi.Tag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lvi.Tag)
        TagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EventOuterClass.internal_static_lvi_Tag_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EventOuterClass.internal_static_lvi_Tag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Tag.class, Builder.class);
      }

      // Construct using lvi.EventOuterClass.Tag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        tagName_ = "";

        tagCode_ = "";

        tagNamespace_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EventOuterClass.internal_static_lvi_Tag_descriptor;
      }

      @Override
      public Tag getDefaultInstanceForType() {
        return Tag.getDefaultInstance();
      }

      @Override
      public Tag build() {
        Tag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Tag buildPartial() {
        Tag result = new Tag(this);
        result.tagName_ = tagName_;
        result.tagCode_ = tagCode_;
        result.tagNamespace_ = tagNamespace_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Tag) {
          return mergeFrom((Tag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Tag other) {
        if (other == Tag.getDefaultInstance()) return this;
        if (!other.getTagName().isEmpty()) {
          tagName_ = other.tagName_;
          onChanged();
        }
        if (!other.getTagCode().isEmpty()) {
          tagCode_ = other.tagCode_;
          onChanged();
        }
        if (!other.getTagNamespace().isEmpty()) {
          tagNamespace_ = other.tagNamespace_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Tag parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Tag) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object tagName_ = "";
      /**
       * <code>string tag_name = 1;</code>
       * @return The tagName.
       */
      public String getTagName() {
        Object ref = tagName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tagName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tag_name = 1;</code>
       * @return The bytes for tagName.
       */
      public com.google.protobuf.ByteString
          getTagNameBytes() {
        Object ref = tagName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tagName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tag_name = 1;</code>
       * @param value The tagName to set.
       * @return This builder for chaining.
       */
      public Builder setTagName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tagName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tag_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTagName() {
        
        tagName_ = getDefaultInstance().getTagName();
        onChanged();
        return this;
      }
      /**
       * <code>string tag_name = 1;</code>
       * @param value The bytes for tagName to set.
       * @return This builder for chaining.
       */
      public Builder setTagNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tagName_ = value;
        onChanged();
        return this;
      }

      private Object tagCode_ = "";
      /**
       * <code>string tag_code = 2;</code>
       * @return The tagCode.
       */
      public String getTagCode() {
        Object ref = tagCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tagCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tag_code = 2;</code>
       * @return The bytes for tagCode.
       */
      public com.google.protobuf.ByteString
          getTagCodeBytes() {
        Object ref = tagCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tagCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tag_code = 2;</code>
       * @param value The tagCode to set.
       * @return This builder for chaining.
       */
      public Builder setTagCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tagCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tag_code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTagCode() {
        
        tagCode_ = getDefaultInstance().getTagCode();
        onChanged();
        return this;
      }
      /**
       * <code>string tag_code = 2;</code>
       * @param value The bytes for tagCode to set.
       * @return This builder for chaining.
       */
      public Builder setTagCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tagCode_ = value;
        onChanged();
        return this;
      }

      private Object tagNamespace_ = "";
      /**
       * <code>string tag_namespace = 3;</code>
       * @return The tagNamespace.
       */
      public String getTagNamespace() {
        Object ref = tagNamespace_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tagNamespace_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tag_namespace = 3;</code>
       * @return The bytes for tagNamespace.
       */
      public com.google.protobuf.ByteString
          getTagNamespaceBytes() {
        Object ref = tagNamespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tagNamespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tag_namespace = 3;</code>
       * @param value The tagNamespace to set.
       * @return This builder for chaining.
       */
      public Builder setTagNamespace(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tagNamespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tag_namespace = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTagNamespace() {
        
        tagNamespace_ = getDefaultInstance().getTagNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string tag_namespace = 3;</code>
       * @param value The bytes for tagNamespace to set.
       * @return This builder for chaining.
       */
      public Builder setTagNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tagNamespace_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lvi.Tag)
    }

    // @@protoc_insertion_point(class_scope:lvi.Tag)
    private static final Tag DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Tag();
    }

    public static Tag getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tag>
        PARSER = new com.google.protobuf.AbstractParser<Tag>() {
      @Override
      public Tag parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tag(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tag> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Tag> getParserForType() {
      return PARSER;
    }

    @Override
    public Tag getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BatchEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lvi.BatchEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
     * @return Whether the actor field is set.
     */
    boolean hasActor();
    /**
     * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
     * @return The actor.
     */
    ActorOuterClass.Actor getActor();
    /**
     * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
     */
    ActorOuterClass.ActorOrBuilder getActorOrBuilder();

    /**
     * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
     */
    java.util.List<Tag>
        getTagsList();
    /**
     * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
     */
    Tag getTags(int index);
    /**
     * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
     */
    int getTagsCount();
    /**
     * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
     */
    java.util.List<? extends TagOrBuilder>
        getTagsOrBuilderList();
    /**
     * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
     */
    TagOrBuilder getTagsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code lvi.BatchEvent}
   */
  public static final class BatchEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lvi.BatchEvent)
      BatchEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BatchEvent.newBuilder() to construct.
    private BatchEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BatchEvent() {
      tags_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new BatchEvent();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BatchEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ActorOuterClass.Actor.Builder subBuilder = null;
              if (actor_ != null) {
                subBuilder = actor_.toBuilder();
              }
              actor_ = input.readMessage(ActorOuterClass.Actor.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(actor_);
                actor_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tags_ = new java.util.ArrayList<Tag>();
                mutable_bitField0_ |= 0x00000001;
              }
              tags_.add(
                  input.readMessage(Tag.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventOuterClass.internal_static_lvi_BatchEvent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventOuterClass.internal_static_lvi_BatchEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BatchEvent.class, Builder.class);
    }

    public static final int ACTOR_FIELD_NUMBER = 1;
    private ActorOuterClass.Actor actor_;
    /**
     * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
     * @return Whether the actor field is set.
     */
    @Override
    public boolean hasActor() {
      return actor_ != null;
    }
    /**
     * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
     * @return The actor.
     */
    @Override
    public ActorOuterClass.Actor getActor() {
      return actor_ == null ? ActorOuterClass.Actor.getDefaultInstance() : actor_;
    }
    /**
     * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
     */
    @Override
    public ActorOuterClass.ActorOrBuilder getActorOrBuilder() {
      return getActor();
    }

    public static final int TAGS_FIELD_NUMBER = 2;
    private java.util.List<Tag> tags_;
    /**
     * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
     */
    @Override
    public java.util.List<Tag> getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
     */
    @Override
    public java.util.List<? extends TagOrBuilder>
        getTagsOrBuilderList() {
      return tags_;
    }
    /**
     * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
     */
    @Override
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
     */
    @Override
    public Tag getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
     */
    @Override
    public TagOrBuilder getTagsOrBuilder(
        int index) {
      return tags_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (actor_ != null) {
        output.writeMessage(1, getActor());
      }
      for (int i = 0; i < tags_.size(); i++) {
        output.writeMessage(2, tags_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (actor_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getActor());
      }
      for (int i = 0; i < tags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, tags_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BatchEvent)) {
        return super.equals(obj);
      }
      BatchEvent other = (BatchEvent) obj;

      if (hasActor() != other.hasActor()) return false;
      if (hasActor()) {
        if (!getActor()
            .equals(other.getActor())) return false;
      }
      if (!getTagsList()
          .equals(other.getTagsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasActor()) {
        hash = (37 * hash) + ACTOR_FIELD_NUMBER;
        hash = (53 * hash) + getActor().hashCode();
      }
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BatchEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BatchEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BatchEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BatchEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BatchEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BatchEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BatchEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BatchEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BatchEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BatchEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BatchEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BatchEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BatchEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lvi.BatchEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lvi.BatchEvent)
        BatchEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EventOuterClass.internal_static_lvi_BatchEvent_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EventOuterClass.internal_static_lvi_BatchEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BatchEvent.class, Builder.class);
      }

      // Construct using lvi.EventOuterClass.BatchEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTagsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (actorBuilder_ == null) {
          actor_ = null;
        } else {
          actor_ = null;
          actorBuilder_ = null;
        }
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EventOuterClass.internal_static_lvi_BatchEvent_descriptor;
      }

      @Override
      public BatchEvent getDefaultInstanceForType() {
        return BatchEvent.getDefaultInstance();
      }

      @Override
      public BatchEvent build() {
        BatchEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BatchEvent buildPartial() {
        BatchEvent result = new BatchEvent(this);
        int from_bitField0_ = bitField0_;
        if (actorBuilder_ == null) {
          result.actor_ = actor_;
        } else {
          result.actor_ = actorBuilder_.build();
        }
        if (tagsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            tags_ = java.util.Collections.unmodifiableList(tags_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tags_ = tags_;
        } else {
          result.tags_ = tagsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BatchEvent) {
          return mergeFrom((BatchEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BatchEvent other) {
        if (other == BatchEvent.getDefaultInstance()) return this;
        if (other.hasActor()) {
          mergeActor(other.getActor());
        }
        if (tagsBuilder_ == null) {
          if (!other.tags_.isEmpty()) {
            if (tags_.isEmpty()) {
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTagsIsMutable();
              tags_.addAll(other.tags_);
            }
            onChanged();
          }
        } else {
          if (!other.tags_.isEmpty()) {
            if (tagsBuilder_.isEmpty()) {
              tagsBuilder_.dispose();
              tagsBuilder_ = null;
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tagsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTagsFieldBuilder() : null;
            } else {
              tagsBuilder_.addAllMessages(other.tags_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BatchEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BatchEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ActorOuterClass.Actor actor_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ActorOuterClass.Actor, ActorOuterClass.Actor.Builder, ActorOuterClass.ActorOrBuilder> actorBuilder_;
      /**
       * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
       * @return Whether the actor field is set.
       */
      public boolean hasActor() {
        return actorBuilder_ != null || actor_ != null;
      }
      /**
       * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
       * @return The actor.
       */
      public ActorOuterClass.Actor getActor() {
        if (actorBuilder_ == null) {
          return actor_ == null ? ActorOuterClass.Actor.getDefaultInstance() : actor_;
        } else {
          return actorBuilder_.getMessage();
        }
      }
      /**
       * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public Builder setActor(ActorOuterClass.Actor value) {
        if (actorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          actor_ = value;
          onChanged();
        } else {
          actorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public Builder setActor(
          ActorOuterClass.Actor.Builder builderForValue) {
        if (actorBuilder_ == null) {
          actor_ = builderForValue.build();
          onChanged();
        } else {
          actorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public Builder mergeActor(ActorOuterClass.Actor value) {
        if (actorBuilder_ == null) {
          if (actor_ != null) {
            actor_ =
              ActorOuterClass.Actor.newBuilder(actor_).mergeFrom(value).buildPartial();
          } else {
            actor_ = value;
          }
          onChanged();
        } else {
          actorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public Builder clearActor() {
        if (actorBuilder_ == null) {
          actor_ = null;
          onChanged();
        } else {
          actor_ = null;
          actorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public ActorOuterClass.Actor.Builder getActorBuilder() {
        
        onChanged();
        return getActorFieldBuilder().getBuilder();
      }
      /**
       * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      public ActorOuterClass.ActorOrBuilder getActorOrBuilder() {
        if (actorBuilder_ != null) {
          return actorBuilder_.getMessageOrBuilder();
        } else {
          return actor_ == null ?
              ActorOuterClass.Actor.getDefaultInstance() : actor_;
        }
      }
      /**
       * <code>.lvi.Actor actor = 1 [(.lvi.required) = false, (.lvi.description) = "Actor concerned with the event"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ActorOuterClass.Actor, ActorOuterClass.Actor.Builder, ActorOuterClass.ActorOrBuilder>
          getActorFieldBuilder() {
        if (actorBuilder_ == null) {
          actorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ActorOuterClass.Actor, ActorOuterClass.Actor.Builder, ActorOuterClass.ActorOrBuilder>(
                  getActor(),
                  getParentForChildren(),
                  isClean());
          actor_ = null;
        }
        return actorBuilder_;
      }

      private java.util.List<Tag> tags_ =
        java.util.Collections.emptyList();
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tags_ = new java.util.ArrayList<Tag>(tags_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Tag, Tag.Builder, TagOrBuilder> tagsBuilder_;

      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public java.util.List<Tag> getTagsList() {
        if (tagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tags_);
        } else {
          return tagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public int getTagsCount() {
        if (tagsBuilder_ == null) {
          return tags_.size();
        } else {
          return tagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Tag getTags(int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);
        } else {
          return tagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Builder setTags(
          int index, Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.set(index, value);
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Builder setTags(
          int index, Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Builder addTags(Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Builder addTags(
          int index, Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(index, value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Builder addTags(
          Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Builder addTags(
          int index, Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Builder addAllTags(
          Iterable<? extends Tag> values) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tags_);
          onChanged();
        } else {
          tagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Builder clearTags() {
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Builder removeTags(int index) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.remove(index);
          onChanged();
        } else {
          tagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Tag.Builder getTagsBuilder(
          int index) {
        return getTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public TagOrBuilder getTagsOrBuilder(
          int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);  } else {
          return tagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public java.util.List<? extends TagOrBuilder>
           getTagsOrBuilderList() {
        if (tagsBuilder_ != null) {
          return tagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tags_);
        }
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Tag.Builder addTagsBuilder() {
        return getTagsFieldBuilder().addBuilder(
            Tag.getDefaultInstance());
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public Tag.Builder addTagsBuilder(
          int index) {
        return getTagsFieldBuilder().addBuilder(
            index, Tag.getDefaultInstance());
      }
      /**
       * <code>repeated .lvi.Tag tags = 2 [(.lvi.description) = "Tags associated with the event"];</code>
       */
      public java.util.List<Tag.Builder>
           getTagsBuilderList() {
        return getTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Tag, Tag.Builder, TagOrBuilder>
          getTagsFieldBuilder() {
        if (tagsBuilder_ == null) {
          tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Tag, Tag.Builder, TagOrBuilder>(
                  tags_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          tags_ = null;
        }
        return tagsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lvi.BatchEvent)
    }

    // @@protoc_insertion_point(class_scope:lvi.BatchEvent)
    private static final BatchEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BatchEvent();
    }

    public static BatchEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BatchEvent>
        PARSER = new com.google.protobuf.AbstractParser<BatchEvent>() {
      @Override
      public BatchEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BatchEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BatchEvent> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BatchEvent> getParserForType() {
      return PARSER;
    }

    @Override
    public BatchEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lvi.Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
     * @return Whether the client field is set.
     */
    boolean hasClient();
    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
     * @return The client.
     */
    ClientOuterClass.Client getClient();
    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
     */
    ClientOuterClass.ClientOrBuilder getClientOrBuilder();

    /**
     * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
     */
    java.util.List<BatchEvent>
        getEventsList();
    /**
     * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
     */
    BatchEvent getEvents(int index);
    /**
     * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
     */
    int getEventsCount();
    /**
     * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
     */
    java.util.List<? extends BatchEventOrBuilder>
        getEventsOrBuilderList();
    /**
     * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
     */
    BatchEventOrBuilder getEventsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code lvi.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lvi.Event)
      EventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Event() {
      events_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Event();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ClientOuterClass.Client.Builder subBuilder = null;
              if (client_ != null) {
                subBuilder = client_.toBuilder();
              }
              client_ = input.readMessage(ClientOuterClass.Client.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(client_);
                client_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                events_ = new java.util.ArrayList<BatchEvent>();
                mutable_bitField0_ |= 0x00000001;
              }
              events_.add(
                  input.readMessage(BatchEvent.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventOuterClass.internal_static_lvi_Event_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventOuterClass.internal_static_lvi_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Event.class, Builder.class);
    }

    public static final int CLIENT_FIELD_NUMBER = 1;
    private ClientOuterClass.Client client_;
    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
     * @return Whether the client field is set.
     */
    @Override
    public boolean hasClient() {
      return client_ != null;
    }
    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
     * @return The client.
     */
    @Override
    public ClientOuterClass.Client getClient() {
      return client_ == null ? ClientOuterClass.Client.getDefaultInstance() : client_;
    }
    /**
     * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
     */
    @Override
    public ClientOuterClass.ClientOrBuilder getClientOrBuilder() {
      return getClient();
    }

    public static final int EVENTS_FIELD_NUMBER = 2;
    private java.util.List<BatchEvent> events_;
    /**
     * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
     */
    @Override
    public java.util.List<BatchEvent> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
     */
    @Override
    public java.util.List<? extends BatchEventOrBuilder>
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
     */
    @Override
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
     */
    @Override
    public BatchEvent getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
     */
    @Override
    public BatchEventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (client_ != null) {
        output.writeMessage(1, getClient());
      }
      for (int i = 0; i < events_.size(); i++) {
        output.writeMessage(2, events_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (client_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getClient());
      }
      for (int i = 0; i < events_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, events_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Event)) {
        return super.equals(obj);
      }
      Event other = (Event) obj;

      if (hasClient() != other.hasClient()) return false;
      if (hasClient()) {
        if (!getClient()
            .equals(other.getClient())) return false;
      }
      if (!getEventsList()
          .equals(other.getEventsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasClient()) {
        hash = (37 * hash) + CLIENT_FIELD_NUMBER;
        hash = (53 * hash) + getClient().hashCode();
      }
      if (getEventsCount() > 0) {
        hash = (37 * hash) + EVENTS_FIELD_NUMBER;
        hash = (53 * hash) + getEventsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lvi.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lvi.Event)
        EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EventOuterClass.internal_static_lvi_Event_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EventOuterClass.internal_static_lvi_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Event.class, Builder.class);
      }

      // Construct using lvi.EventOuterClass.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEventsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (clientBuilder_ == null) {
          client_ = null;
        } else {
          client_ = null;
          clientBuilder_ = null;
        }
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EventOuterClass.internal_static_lvi_Event_descriptor;
      }

      @Override
      public Event getDefaultInstanceForType() {
        return Event.getDefaultInstance();
      }

      @Override
      public Event build() {
        Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Event buildPartial() {
        Event result = new Event(this);
        int from_bitField0_ = bitField0_;
        if (clientBuilder_ == null) {
          result.client_ = client_;
        } else {
          result.client_ = clientBuilder_.build();
        }
        if (eventsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            events_ = java.util.Collections.unmodifiableList(events_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.events_ = events_;
        } else {
          result.events_ = eventsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Event) {
          return mergeFrom((Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Event other) {
        if (other == Event.getDefaultInstance()) return this;
        if (other.hasClient()) {
          mergeClient(other.getClient());
        }
        if (eventsBuilder_ == null) {
          if (!other.events_.isEmpty()) {
            if (events_.isEmpty()) {
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEventsIsMutable();
              events_.addAll(other.events_);
            }
            onChanged();
          }
        } else {
          if (!other.events_.isEmpty()) {
            if (eventsBuilder_.isEmpty()) {
              eventsBuilder_.dispose();
              eventsBuilder_ = null;
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000001);
              eventsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEventsFieldBuilder() : null;
            } else {
              eventsBuilder_.addAllMessages(other.events_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Event) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ClientOuterClass.Client client_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ClientOuterClass.Client, ClientOuterClass.Client.Builder, ClientOuterClass.ClientOrBuilder> clientBuilder_;
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
       * @return Whether the client field is set.
       */
      public boolean hasClient() {
        return clientBuilder_ != null || client_ != null;
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
       * @return The client.
       */
      public ClientOuterClass.Client getClient() {
        if (clientBuilder_ == null) {
          return client_ == null ? ClientOuterClass.Client.getDefaultInstance() : client_;
        } else {
          return clientBuilder_.getMessage();
        }
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
       */
      public Builder setClient(ClientOuterClass.Client value) {
        if (clientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          client_ = value;
          onChanged();
        } else {
          clientBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
       */
      public Builder setClient(
          ClientOuterClass.Client.Builder builderForValue) {
        if (clientBuilder_ == null) {
          client_ = builderForValue.build();
          onChanged();
        } else {
          clientBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
       */
      public Builder mergeClient(ClientOuterClass.Client value) {
        if (clientBuilder_ == null) {
          if (client_ != null) {
            client_ =
              ClientOuterClass.Client.newBuilder(client_).mergeFrom(value).buildPartial();
          } else {
            client_ = value;
          }
          onChanged();
        } else {
          clientBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
       */
      public Builder clearClient() {
        if (clientBuilder_ == null) {
          client_ = null;
          onChanged();
        } else {
          client_ = null;
          clientBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
       */
      public ClientOuterClass.Client.Builder getClientBuilder() {
        
        onChanged();
        return getClientFieldBuilder().getBuilder();
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
       */
      public ClientOuterClass.ClientOrBuilder getClientOrBuilder() {
        if (clientBuilder_ != null) {
          return clientBuilder_.getMessageOrBuilder();
        } else {
          return client_ == null ?
              ClientOuterClass.Client.getDefaultInstance() : client_;
        }
      }
      /**
       * <code>.lvi.Client client = 1 [(.lvi.required) = false, (.lvi.description) = "Owner of the event"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ClientOuterClass.Client, ClientOuterClass.Client.Builder, ClientOuterClass.ClientOrBuilder>
          getClientFieldBuilder() {
        if (clientBuilder_ == null) {
          clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ClientOuterClass.Client, ClientOuterClass.Client.Builder, ClientOuterClass.ClientOrBuilder>(
                  getClient(),
                  getParentForChildren(),
                  isClean());
          client_ = null;
        }
        return clientBuilder_;
      }

      private java.util.List<BatchEvent> events_ =
        java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          events_ = new java.util.ArrayList<BatchEvent>(events_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          BatchEvent, BatchEvent.Builder, BatchEventOrBuilder> eventsBuilder_;

      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public java.util.List<BatchEvent> getEventsList() {
        if (eventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(events_);
        } else {
          return eventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public int getEventsCount() {
        if (eventsBuilder_ == null) {
          return events_.size();
        } else {
          return eventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public BatchEvent getEvents(int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);
        } else {
          return eventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public Builder setEvents(
          int index, BatchEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.set(index, value);
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public Builder setEvents(
          int index, BatchEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public Builder addEvents(BatchEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public Builder addEvents(
          int index, BatchEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(index, value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public Builder addEvents(
          BatchEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public Builder addEvents(
          int index, BatchEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public Builder addAllEvents(
          Iterable<? extends BatchEvent> values) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, events_);
          onChanged();
        } else {
          eventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public Builder clearEvents() {
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public Builder removeEvents(int index) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.remove(index);
          onChanged();
        } else {
          eventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public BatchEvent.Builder getEventsBuilder(
          int index) {
        return getEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public BatchEventOrBuilder getEventsOrBuilder(
          int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);  } else {
          return eventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public java.util.List<? extends BatchEventOrBuilder>
           getEventsOrBuilderList() {
        if (eventsBuilder_ != null) {
          return eventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(events_);
        }
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public BatchEvent.Builder addEventsBuilder() {
        return getEventsFieldBuilder().addBuilder(
            BatchEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public BatchEvent.Builder addEventsBuilder(
          int index) {
        return getEventsFieldBuilder().addBuilder(
            index, BatchEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .lvi.BatchEvent events = 2 [(.lvi.required) = true, (.lvi.batch_attribute) = true];</code>
       */
      public java.util.List<BatchEvent.Builder>
           getEventsBuilderList() {
        return getEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          BatchEvent, BatchEvent.Builder, BatchEventOrBuilder>
          getEventsFieldBuilder() {
        if (eventsBuilder_ == null) {
          eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              BatchEvent, BatchEvent.Builder, BatchEventOrBuilder>(
                  events_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        return eventsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lvi.Event)
    }

    // @@protoc_insertion_point(class_scope:lvi.Event)
    private static final Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Event();
    }

    public static Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Event>
        PARSER = new com.google.protobuf.AbstractParser<Event>() {
      @Override
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Event> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    @Override
    public Event getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lvi_Tag_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lvi_Tag_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lvi_BatchEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lvi_BatchEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lvi_Event_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lvi_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022protos/event.proto\022\003lvi\032\035protos/bigque" +
      "ry_options.proto\032\023protos/client.proto\032\022p" +
      "rotos/actor.proto\"@\n\003Tag\022\020\n\010tag_name\030\001 \001" +
      "(\t\022\020\n\010tag_code\030\002 \001(\t\022\025\n\rtag_namespace\030\003 " +
      "\001(\t\"\210\001\n\nBatchEvent\022?\n\005actor\030\001 \001(\0132\n.lvi." +
      "ActorB$\220?\000\242?\036Actor concerned with the ev" +
      "ent\0229\n\004tags\030\002 \003(\0132\010.lvi.TagB!\242?\036Tags ass" +
      "ociated with the event\"m\n\005Event\0225\n\006clien" +
      "t\030\001 \001(\0132\013.lvi.ClientB\030\220?\000\242?\022Owner of the" +
      " event\022\'\n\006events\030\002 \003(\0132\017.lvi.BatchEventB" +
      "\006\220?\001\250?\001:\004\220\202\031\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          BigqueryOptions.getDescriptor(),
          ClientOuterClass.getDescriptor(),
          ActorOuterClass.getDescriptor(),
        });
    internal_static_lvi_Tag_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lvi_Tag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lvi_Tag_descriptor,
        new String[] { "TagName", "TagCode", "TagNamespace", });
    internal_static_lvi_BatchEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lvi_BatchEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lvi_BatchEvent_descriptor,
        new String[] { "Actor", "Tags", });
    internal_static_lvi_Event_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lvi_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lvi_Event_descriptor,
        new String[] { "Client", "Events", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(BigqueryOptions.batchAttribute);
    registry.add(BigqueryOptions.description);
    registry.add(BigqueryOptions.required);
    registry.add(BigqueryOptions.tableRoot);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    BigqueryOptions.getDescriptor();
    ClientOuterClass.getDescriptor();
    ActorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
