// Generated by the proto-to-bq Proto compiler plugin.  DO NOT EDIT!
package lvi;

import com.google.api.services.bigquery.model.TableRow;
import com.google.api.services.bigquery.model.TableCell;

import java.util.LinkedList;

public final class EventParser {
	public static LinkedList<TableRow> convertToTableRow(EventOuterClass.Event event) throws Exception {
		LinkedList<TableRow> rows = new LinkedList<TableRow>();
		TableRow common = new TableRow();
		
		// client
		TableCell client = new TableCell();
		if(event.hasClient()) {
			client.set("name", event.getClient().getName());
			if(event.getClient().hasTenantId()) {
				client.set("tenantId", event.getClient().getTenantId());
			}
		}
		common.set("client", client);
		for(EventOuterClass.BatchEvent events: event.getEventsList()) {
			TableRow row = new TableRow();
			LinkedList<TableCell> tagsCells = new LinkedList<TableCell>();
			for(EventOuterClass.Tag tags: events.getTagsList()) {
				TableCell tagsCell = new TableCell();
				tagsCell.set("tag_namespace", tags.getTagNamespace());
				tagsCell.set("tag_code", tags.getTagCode());
				tagsCell.set("tag_name", tags.getTagName());
				tagsCells.add(tagsCell);
			}
			row.set("tags", tagsCells);
			
			// actor
			TableCell actor = new TableCell();
			if(events.hasActor()) {
				
				// address
				TableCell address = new TableCell();
				if(events.getActor().hasAddress()) {
					address.set("country", events.getActor().getAddress().getCountry());
					address.set("number", events.getActor().getAddress().getNumber());
					address.set("street", events.getActor().getAddress().getStreet());
				}
				actor.set("address", address);
				if(events.getActor().hasEmail()) {
					actor.set("email", events.getActor().getEmail());
				}
				if(events.getActor().hasUserId()) {
					actor.set("userId", events.getActor().getUserId());
				}
			}
			row.set("actor", actor);
			row.setF(common.getF());
			rows.add(row);
		}
		return rows;
	}
}
